config/routes.rb
Rails.application.routes.draw do
  get 'todo/index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :task, presence: true,
                  length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to @todo
    else
      render 'new'
    end
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todo_params)
      redirect_to @todo
    else
      render 'edit'
    end
  end

  def destroy
    @todo = Todo.find(params[:id])

    @todo.destroy
    redirect_to todos_path
  end

  private
    def todo_params
      params.require(:todo).permit(:completed, :task)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
<% if @todo.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@todo.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <p>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </p>
  <p>
    <%= f.label :task %> <br>
    <%= f.text_area :task %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/todos/edit.html.erb
<h2>Editar tarea</h2>

<%= render 'form' %>

<%= link_to 'Atras', todos_path %>

app/views/todos/index.html.erb
<h1>Tareas</h1>
<table>
  <tr>
    <th>Complete</th>
    <th>Tareas</th>
  </tr>
  <% @todos.each do |todo| %>
    <tr>
      <td><input type="checkbox" disabled <% if todo.completed == 1 %> checked <% end %> /></td>
      <td><%= todo.task %></td>
      <td><%= link_to 'Mostrar', todo_path(todo) %></td>
      <td><%= link_to 'Editar', edit_todo_path(todo) %></td>
      <td><%= link_to 'Eliminar', todo_path(todo),
              method: :delete,
              data: { confirm: 'Estas seguro(a)?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Nuevo', new_todo_path %>

app/views/todos/new.html.erb
<h2>Nueva tarea</h2>

<%= render 'form' %>

<%= link_to 'Atras', todos_path %>

app/views/todos/show.html.erb
<p>
  <strong>
    Completed:
  </strong>
  <td><input type="checkbox" disabled <% if @todo.completed == 1 %> checked <% end %> /></td>
</p>
<p>
  <strong>Task:</strong>
  <%= @todo.task %>
</p>
<p>
  <%= link_to 'Tareas', todos_path %>
</p>